plugins {
    application
}

group = "org.mockbukkit.integrationtester"
version = "0.1.0"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    mavenLocal()
}

dependencies {
    implementation("com.palantir.javapoet:javapoet:0.6.0")
    implementation("io.papermc.paper:paper-api:1.21.3-R0.1-SNAPSHOT")
    implementation("io.github.classgraph:classgraph:4.8.177")
}

tasks {
    application {
        mainClass = "org.mockbukkit.integrationtester.codegen.CodeGenerator"
    }

    getByName<JavaExec>("run") {
        args = listOf(rootProject.projectDir.resolve("test-client/src/autogenerated/java").absolutePath)
    }
}