plugins {
    id("java")
}

group = "org.mockbukkit.integrationtester"
version = "0.1.0"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

java {
    toolchain{
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        java.srcDir(file("src/main/java"))
        java.srcDir(file("src/autogenerated/java"))
    }
}

dependencies {
    implementation("org.mockito:mockito-core:5.15.2")
    implementation("org.junit.jupiter:junit-jupiter:5.11.3")
    compileOnly("io.papermc.paper:paper-api:1.21.3-R0.1-SNAPSHOT")
    implementation("org.testcontainers:yugabytedb:1.20.4")
}

tasks.test {
    useJUnitPlatform()
}